In [ ]:
from keras.layers import *
from keras.models import Model
from keras.losses import binary_crossentropy
import numpy as np
import warnings
warnings.filterwarnings("ignore")


In [6]:
DIM_EMBEDDING = 100
LEN_VOC = 1000
LSTM_UNIT1 = 32
LSTM_UNIT2 = 16
LEN_S1 = 50
LEN_S2 = 40
BATCH_SIZE = 8

## 测试Dot层是否为矩阵乘法的结果

In [28]:
len_s1 = 3
len_s2 = 5
dim_embedding = 4
s1 = Input(batch_shape=[None, len_s1, dim_embedding], name='sen1')
s2 = Input(batch_shape=[None, len_s2, dim_embedding], name='sen2')

dot1 = Dot(axes=-1, name='s1_dot_s2')([s1, s2])
dot2 = Dot(axes=-1, name='s2_dot_s1')([s2, s1])
model = Model(inputs=[s1, s2], outputs=[dot1, dot2])
model.compile(optimizer='sgd', loss=binary_crossentropy)
model.summary()


__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
sen1 (InputLayer)               (None, 3, 4)         0                                            
__________________________________________________________________________________________________
sen2 (InputLayer)               (None, 5, 4)         0                                            
__________________________________________________________________________________________________
s1_dot_s2 (Dot)                 (None, 3, 5)         0           sen1[0][0]                       
                                                                 sen2[0][0]                       
__________________________________________________________________________________________________
s2_dot_s1 (Dot)                 (None, 5, 3)         0           sen2[0][0]                       
          

In [29]:
x1 = np.random.randint(10, size=[BATCH_SIZE, len_s1, dim_embedding])
x2 = np.random.randint(10, size=[BATCH_SIZE, len_s2, dim_embedding])
print('x1[:1]\n\n', x1[:1])
print('x2[:1]\n\n', x2[:1])
y1, y2 = model.predict(x=[x1, x2])
print('y1[:1]\n\n', y1[:1])
print('y2[:1]\n\n', y2[:1])

x1[:1]

 [[[5 8 6 3]
  [1 1 5 7]
  [0 4 5 9]]]
x2[:1]

 [[[1 2 1 4]
  [9 1 5 2]
  [6 6 8 3]
  [4 5 1 7]
  [0 0 3 4]]]
y1[:1]

 [[[ 39.  89. 135.  87.  30.]
  [ 36.  49.  73.  63.  43.]
  [ 49.  47.  91.  88.  51.]]]
y2[:1]

 [[[ 39.  36.  49.]
  [ 89.  49.  47.]
  [135.  73.  91.]
  [ 87.  63.  88.]
  [ 30.  43.  51.]]]


## 结果
可以看出Dot能完成矩阵乘法，但前提是两者A/B相乘的维度相同，并且传入参数的顺序决定矩阵相乘时的顺序，如果是Dot(axes=-1)([A,B]),结果为C = A \* B.T，如果顺序相反则为C = B \* A.T